language: php
php:
- 5.5
- 5.6
- hhvm
- 7
matrix:
  include:
    - php: 5.5
      after_script:
      - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist
script:
- phpunit --coverage-text --coverage-clover=coverage.clover
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/56fbdc2d0c44773dc740
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false