# Usefull links
# =============
# https://hub.docker.com/_/php/
# https://docs.docker.com/compose/overview/
# https://docs.docker.com/compose/compose-file/
#
# Usefull commands
# ================
#
# Connect into command line of container
# $ docker-compose up -d && docker exec -it cli_json_api /bin/bash
# Tip: `Ctrl+p` + `Ctrl+q` + `Enter` (to exit container bash)
#
# Remove containers
# $ docker-compose down
#
# In container
# ------------
# Run test suit
# $ cd /app && ./vendor/bin/phpunit
# Performance test
# $ cd /app/sample/ && time php sample.php -t=10000

cli:
  image: php:cli
  container_name: cli_json_api
  volumes:
    - .:/app
  working_dir: /app
  tty: true
